template: 'facelessuser:master-labels:labels.yml:master'

# Wildcard labels

brace_expansion: true
extended_glob: true

rules:
  - labels: ['C: infrastructure']
    patterns: ['*|{tools,requirements,.github}/**|-*.md']

  - labels: ['C: source']
    patterns: ['rummage/**']

  - labels: ['C: tests']
    patterns: ['tests/**']

  - labels: ['C: docs']
    patterns: ['docs/**|*.md']

  - labels: ['C: gui']
    patterns: ['rummage/lib/gui/**']

  - labels: ['C: search-replace']
    patterns: ['rummage/lib/rumcore/**|tests/**/test_{rumcore,text_decode}.py']

  - labels: ['C: localization']
    patterns: ['rummage/lib/gui/localization/**']

  - labels: ['C: notifications']
    patterns: ['rummage/lib/gui/notify/**']

  - labels: ['C: data']
    patterns: ['rummage/lib/gui/data/**']

  - labels: ['C: dialogs']
    patterns: ['rummage/lib/gui/dialogs/**']

  - labels: ['C: controls']
    patterns: ['rummage/lib/gui/controls/**']

  - labels: ['C: settings']
    patterns: ['rummage/lib/gui/settings/**']

  - labels: ['C: app']
    patterns: ['rummage/lib/gui/app/**']

  - labels: ['C: actions']
    patterns: ['rummage/lib/gui/actions/**']

# Label Management

labels:
- name: 'C: search-replace'
  renamed: search-replace
  color: subcategory
  description: Related to the search and replace logic.

- name: 'C: gui'
  renamed: gui
  color: subcategory
  description: Related to the GUI.

- name: 'C: localization'
  renamed: localization
  color: subcategory
  description: Related to localization.

- name: 'C: notifications'
  renamed: notifications
  color: subcategory
  description: Related to notifications.

- name: 'C: data'
  renamed: data
  color: subcategory
  description: Related to data.

- name: 'C: dialogs'
  renamed: dialogs
  color: subcategory
  description: Related to GUI dialogs.

- name: 'C: controls'
  renamed: controls
  color: subcategory
  description: Related to GUI controls.

- name: 'C: settings'
  renamed: settings
  color: subcategory
  description: Related to settings managment.

- name: 'C: app'
  renamed: app
  color: subcategory
  description: Related to application level code.

- name: 'C: actions'
  renamed: actions
  color: subcategory
  description: Related to GUI actions.
