# Wildcard labels

brace_expansion: true
extended_glob: true

rules:
  - labels: [infrastructure]
    patterns: ['*|{tools,requirements,.github}/**|-README.md']

  - labels: [source]
    patterns: ['rummage/**']

  - labels: [tests]
    patterns: ['tests/**']

  - labels: [docs]
    patterns: ['docs/**|README.md']

  - labels: [gui]
    patterns: ['rummage/lib/gui/**']

  - labels: [search-replace]
    patterns: ['rummage/lib/rumcore/**|tests/**/test_{rumcore,text_decode}.py']

  - labels: [localization]
    patterns: ['rummage/lib/gui/localization/**']

  - labels: [notifications]
    patterns: ['rummage/lib/gui/notify/**']

  - labels: [data]
    patterns: ['rummage/lib/gui/data/**']

  - labels: [dialogs]
    patterns: ['rummage/lib/gui/dialogs/**']

  - labels: [controls]
    patterns: ['rummage/lib/gui/controls/**']

  - labels: [settings]
    patterns: ['rummage/lib/gui/settings/**']

  - labels: [app]
    patterns: ['rummage/lib/gui/app/**']

  - labels: [actions]
    patterns: ['rummage/lib/gui/actions/**']

# WIP labels

wip:
  - work-in-progress
  - needs-review
  - needs-decision
  - needs-confirmation
  - requires-changes
  - rejected

# Label Management

delete_labels: true

colors:
  bug: '#c45b46'
  feature: '#7b17d8'
  support: '#efbe62'
  maintenance: '#b2ffeb'
  category: '#709ad8'
  subcategory: '#bfd4f2'
  pending: '#f0f49a'
  rejected: '#f7c7be'
  approved: '#beed6d'
  low: '#dddddd'
  bot: '#000000'

labels:
- name: bug
  color: bug
  description: Bug report.

- name: feature
  color: feature
  description: Feature request.

- name: maintenance
  color: maintenance
  description: Maintenance chore.

- name: support
  color: support
  description: Support request.

- name: tests
  color: category
  description: Related to testing.

- name: infrastructure
  color: category
  description: Related to project infrastructure.

- name: source
  color: category
  description: Related to source code.

- name: docs
  color: category
  description: Related to documentation.

- name: search-replace
  color: subcategory
  description: Related to the search and replace logic.

- name: gui
  renamed: user-interface
  color: subcategory
  description: Related to the GUI.

- name: localization
  color: subcategory
  description: Related to localization.

- name: notifications
  color: subcategory
  description: Related to notifications.

- name: data
  color: subcategory
  description: Related to data.

- name: dialogs
  color: subcategory
  description: Related to GUI dialogs.

- name: controls
  color: subcategory
  description: Related to GUI controls.

- name: settings
  color: subcategory
  description: Related to settings managment.

- name: app
  color: subcategory
  description: Related to application level code.

- name: actions
  color: subcategory
  description: Related to GUI actions.

- name: triage
  color: pending
  description: Issue needs triage.

- name: more-info-needed
  color: pending
  description: More information is required.

- name: needs-confirmation
  color: pending
  description: The alleged behavior needs to be confirmed.

- name: needs-decision
  color: pending
  description: A decision needs to be made regarding request.

- name: confirmed
  color: approved
  description: Confirmed bug report or approved feature request.

- name: maybe
  color: low
  description: Pending approval of low priority request.

- name: duplicate
  color: rejected
  description: The issue has been previously reported.

- name: wontfix
  color: rejected
  description: The issue will not be fixed for the stated reasons.

- name: invalid
  color: rejected
  description: Invalid report (user error, upstream issue, etc).

- name: work-in-progress
  color: pending
  description: A partial solution. More changes will be coming.

- name: needs-review
  color: pending
  description: Needs to be reviewed and/or approved.

- name: requires-changes
  color: pending
  description: Awaiting updates after a review.

- name: approved
  color: approved
  description: The pull request is ready to be merged.

- name: rejected
  color: rejected
  description: The pull request is rejected for the stated reasons.

- name: skip-triage
  color: bot
  description: Tells bot to not tag a new issue with 'triage'.

- name: skip-review
  color: bot
  description: Tells bot to not tag a reviews with 'needs-review'.
