brace_expansion: true
extended_glob: true

rules:
  - labels: [infrastructure]
    patterns: ['*|{tools,requirements,.github}/**|-README.md']

  - labels: [source]
    patterns: ['rummage/**']

  - labels: [tests]
    patterns: ['tests/**']

  - labels: [docs]
    patterns: ['docs/**|README.md']

  - labels: [gui]
    patterns: ['rummage/lib/gui/**']

  - labels: [search-replace]
    patterns: ['rummage/lib/rumcore/**|tests/**/test_{rumcore,text_decode}.py']

  - labels: [localization]
    patterns: ['rummage/lib/gui/localization/**']

  - labels: [notifications]
    patterns: ['rummage/lib/gui/notify/**']

  - labels: [data]
    patterns: ['rummage/lib/gui/data/**']

  - labels: [dialogs]
    patterns: ['rummage/lib/gui/dialogs/**']

  - labels: [controls]
    patterns: ['rummage/lib/gui/controls/**']

  - labels: [settings]
    patterns: ['rummage/lib/gui/settings/**']

  - labels: [app]
    patterns: ['rummage/lib/gui/app/**']

  - labels: [actions]
    patterns: ['rummage/lib/gui/actions/**']
